# Generated by Django 2.2.12 on 2024-10-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃（伪删除）'),
        ),
    ]
