# Generated by Django 2.2.12 on 2024-10-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.CharField(max_length=120, verbose_name='个人描述'),
        ),
    ]
